version: "3"
services:
  db:
    container_name: db
    restart: on-failure
    image: postgres:13
    volumes:
      - ./quidditch-iutm-server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "6000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  server:
    container_name: server
    restart: on-failure
    build: quidditch-iutm-server
    depends_on:
      - db
    links:
      - db
    ports:
      - "8000:80"
    environment:
      DB_SERVER: db
      DB_PORT: 5432
  client:
    container_name: client
    restart: on-failure
    build: quidditch-iutm-client
    ports:
    - "3000:3000"
