version: "3"
services:
  postgres:
    container_name: postgres
    restart: on-failure
    image: postgres:13
    volumes:
      - ./quidditch-iutm-server/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5000:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db
  server:
    container_name: server
    restart: on-failure
    build: quidditch-iutm-server
    depends_on:
      - postgres
    ports:
      - "8080:80"
  client:
    container_name: client
    restart: on-failure
    build: quidditch-iutm-client
    ports:
    - "3000:3000"
